### ISSUE TITLE
Multi user

### ISSUE THREAD

**Issue by tasker-kounkou** [kounkou/Staples#5]
Staples shall provide multiuser access To Staples. This will allow different users to access the database and use the application without installing an arduino at home.

**Comment by tasker-kounkou** [comment]
http://doc.qt.io/qt-4.8/qhttpmultipart.html

**Comment by kounkou** [comment]
@pacoSAM @josuebrunel any idea how to manage the user accounts ?

**Comment by josuebrunel** [comment]
> @pacoSAM @josuebrunel any idea how to manage the user accounts ?

Yep, i have couple ideas. Will detail and surely submit a couple patches this weekend

**Comment by kounkou** [comment]
Found a very interesting post on Qt.
However, the API seems to be available from Qt 5.8,...
http://blog.qt.io/blog/2017/01/25/connecting-qt-application-google-services-using-oauth-2-0/
